/**
 * actions generated by the MapForm component
 */

/** 
 * dispatched when cafe checkbox toggled on or off 
 */
export const CAFE_CHECKBOX_TOGGLED = "CAFE_CHECKBOX_TOGGLED";
export function cafeCheckboxToggled(payload: boolean) {
    return {
        type: CAFE_CHECKBOX_TOGGLED,
        payload
    }
}

/** 
 * dispatched when library checkbox toggled on or off 
 */
export const LIBRARY_CHECKBOX_TOGGLED = "LIBRARY_CHECKBOX_TOGGLED";
export function libraryCheckboxToggled(payload: boolean) {
    return {
        type: LIBRARY_CHECKBOX_TOGGLED,
        payload
    }
}

/** 
 * dispatched when book_store checkbox toggled on or off 
 */
export const BOOK_STORE_CHECKBOX_TOGGLED = "BOOK_STORE_CHECKBOX_TOGGLED";
export function bookStoreCheckboxToggled(payload: boolean) {
    return {
        type: BOOK_STORE_CHECKBOX_TOGGLED,
        payload
    }
}

/** 
 * dispatched when a new location is submitted (payload is new location) 
 */
export const LOCATION_FORM_SUBMITTED = "LOCATION_FORM_SUBMITTED";
export function locationFormSubmitted(payload: string) {
    return {
        type: LOCATION_FORM_SUBMITTED,
        payload
    }
}